modLoader="javafml"
loaderVersion="[36,)"
license="All rights reserved"
[[mods]]
modId="moarenergistics"
version="${file.jarVersion}"
displayName="MoarEnergistics"
credits=""
authors="OneLousyDev"
description='''
A mod which contains some useful extras for AppliedEnergistics in modern Minecraft versions!
'''
[[dependencies.moarenergistics]]
    modId="forge"
    mandatory=true
    versionRange="[36,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.moarenergistics]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.5,1.17)"
    ordering="NONE"
    side="BOTH"
[[dependencies.moarenergistics]]
    modId="appliedenergistics2"
    mandatory=true
    versionRange="[8.4.0,8.4.3)"
    ordering="NONE"
    side="BOTH"
